# Generated by Django 5.2rc1 on 2025-03-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=50)),
                ('lastName', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('rePassword', models.CharField()),
            ],
        ),
    ]
